acme_store_homepage:
    path:   /hello/{name}
    defaults: { _controller: AcmeStoreBundle:Default:index }
create:
    path:   /create
    defaults: { _controller: AcmeStoreBundle:Default:create }
get_all:
    path:   /all
    defaults: { _controller: AcmeStoreBundle:Default:all }
update:
    path:   /update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update }
remove:
    path:   /remove/{id}
    defaults: { _controller: AcmeStoreBundle:Default:remove }
pricemore:
    path:   /pricemore/{price}
    defaults: { _controller: AcmeStoreBundle:Default:pricemore, price: 25.99 }
    methods:  [GET, POST]